/* X Coder service worker.
 * - Precaches the whole app (atomic, versioned) so X Coder opens offline from the Home Screen.
 * - Updates install in the background; the page offers "Reload to Update" (or updates
 *   immediately when upgrading from X Coder 5).
 * - Runtime-caches CDN libraries (Pyodide, Prettier, esm.sh packages, Puter.js) for offline reuse.
 * The VERSION and PRECACHE lists are generated by tools/gen-sw.mjs — do not edit them by hand.
 */

const VERSION = 'xcoder-6.0.0-7f31ecdfb8cd'; // @generated
const PRECACHE = ["./css/chat.css",
  "./css/editor.css",
  "./css/explorer.css",
  "./css/extensions.css",
  "./css/panel.css",
  "./css/preview.css",
  "./css/scm.css",
  "./css/search.css",
  "./css/settings.css",
  "./css/theme.css",
  "./css/welcome.css",
  "./css/widgets.css",
  "./css/workbench.css",
  "./icons/app-icon-512.svg",
  "./icons/app-icon.svg",
  "./icons/apple-touch-icon-v51.svg",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/letterpress.svg",
  "./index.html",
  "./manifest.webmanifest",
  "./src/ai/api.js",
  "./src/ai/engine.js",
  "./src/ai/index.js",
  "./src/cloud/index.js",
  "./src/core/commands.js",
  "./src/core/db.js",
  "./src/core/diagnostics.js",
  "./src/core/dom.js",
  "./src/core/events.js",
  "./src/core/fs.js",
  "./src/core/menus.js",
  "./src/core/output.js",
  "./src/core/path.js",
  "./src/core/puter.js",
  "./src/core/settings.js",
  "./src/core/templates.js",
  "./src/core/workspace.js",
  "./src/editor/api.js",
  "./src/editor/index.js",
  "./src/main.js",
  "./src/panel/api.js",
  "./src/panel/index.js",
  "./src/platform/contextmenu.js",
  "./src/platform/dialogs.js",
  "./src/platform/notifications.js",
  "./src/platform/quickinput.js",
  "./src/preview/api.js",
  "./src/preview/index.js",
  "./src/scm/api.js",
  "./src/scm/index.js",
  "./src/views/explorer.js",
  "./src/views/extensions.js",
  "./src/views/files-api.js",
  "./src/views/run.js",
  "./src/views/search.js",
  "./src/views/settingsEditor.js",
  "./src/views/welcome.js",
  "./src/workbench/contributions.js",
  "./src/workbench/coreCommands.js",
  "./src/workbench/editors.js",
  "./src/workbench/icons.js",
  "./src/workbench/layout.js",
  "./src/workbench/panel.js",
  "./src/workbench/statusbar.js",
  "./src/workbench/theme.js",
  "./src/workbench/titlebar.js",
  "./src/workbench/views.js",
  "./vendor/acorn.js",
  "./vendor/chunks/apl-RHGJ6ATI.js",
  "./vendor/chunks/asciiarmor-QXBRRPTB.js",
  "./vendor/chunks/asn1-SLR4RN4C.js",
  "./vendor/chunks/asterisk-XXV7RMES.js",
  "./vendor/chunks/brainfuck-2LYBMVMY.js",
  "./vendor/chunks/chunk-AWNCJPH5.js",
  "./vendor/chunks/chunk-EK4JQTFQ.js",
  "./vendor/chunks/chunk-EMBIDUMY.js",
  "./vendor/chunks/chunk-L4HOG767.js",
  "./vendor/chunks/chunk-PZDV5WLV.js",
  "./vendor/chunks/chunk-S6BMAXLK.js",
  "./vendor/chunks/chunk-UZ6FUKPV.js",
  "./vendor/chunks/chunk-VD3L363Y.js",
  "./vendor/chunks/chunk-VJQ62HL7.js",
  "./vendor/chunks/chunk-WYZ5ZH2W.js",
  "./vendor/chunks/chunk-Z3QOKH62.js",
  "./vendor/chunks/clike-QLHXI4P3.js",
  "./vendor/chunks/clojure-CJCS5IF2.js",
  "./vendor/chunks/cmake-SA2CV22R.js",
  "./vendor/chunks/cobol-3NXHWYI3.js",
  "./vendor/chunks/coffeescript-23YZIAIK.js",
  "./vendor/chunks/commonlisp-4EEUTM2K.js",
  "./vendor/chunks/crystal-J2C5ATOZ.js",
  "./vendor/chunks/css-5SK5OWC5.js",
  "./vendor/chunks/cypher-2PS4Z73B.js",
  "./vendor/chunks/d-F6J2W5UR.js",
  "./vendor/chunks/diff-2JRKEV4F.js",
  "./vendor/chunks/dist-3ASTAYA4.js",
  "./vendor/chunks/dist-3YEYI44A.js",
  "./vendor/chunks/dist-456MQHP5.js",
  "./vendor/chunks/dist-47AMTZ55.js",
  "./vendor/chunks/dist-4SC63NH7.js",
  "./vendor/chunks/dist-7PDZT7IN.js",
  "./vendor/chunks/dist-CZAHIZNU.js",
  "./vendor/chunks/dist-FTT7D7MD.js",
  "./vendor/chunks/dist-GFSCCZ4T.js",
  "./vendor/chunks/dist-HPKV2Q6G.js",
  "./vendor/chunks/dist-JS65VNUD.js",
  "./vendor/chunks/dist-JUHB4HWL.js",
  "./vendor/chunks/dist-L22EVTGR.js",
  "./vendor/chunks/dist-MYCVJ5K4.js",
  "./vendor/chunks/dist-OF6ASR3S.js",
  "./vendor/chunks/dist-OLYAFRXW.js",
  "./vendor/chunks/dist-QOCXKLCW.js",
  "./vendor/chunks/dist-S2Y5ZIWT.js",
  "./vendor/chunks/dist-W2SRI6SF.js",
  "./vendor/chunks/dist-WJGKQCU5.js",
  "./vendor/chunks/dist-WY2H5GYH.js",
  "./vendor/chunks/dockerfile-ZLFF3E5E.js",
  "./vendor/chunks/dtd-JHJNXI7N.js",
  "./vendor/chunks/dylan-QJGZLPCU.js",
  "./vendor/chunks/ebnf-CQHP2HNU.js",
  "./vendor/chunks/ecl-NN4V4S2K.js",
  "./vendor/chunks/eiffel-26UJCTHV.js",
  "./vendor/chunks/elm-XF5XBBPZ.js",
  "./vendor/chunks/erlang-QTW535T2.js",
  "./vendor/chunks/factor-SPIMT6C4.js",
  "./vendor/chunks/fcl-AIHVPGWM.js",
  "./vendor/chunks/forth-UDX2ZKEQ.js",
  "./vendor/chunks/fortran-FMFYP2UA.js",
  "./vendor/chunks/gas-IKHZUMWA.js",
  "./vendor/chunks/gherkin-2Z7WZMOA.js",
  "./vendor/chunks/groovy-ZK6BEDYD.js",
  "./vendor/chunks/haskell-FHBDWUOY.js",
  "./vendor/chunks/haxe-I7GY5J5I.js",
  "./vendor/chunks/http-2AU2V3EV.js",
  "./vendor/chunks/idl-RDKPMRMM.js",
  "./vendor/chunks/javascript-FAYP2DAH.js",
  "./vendor/chunks/julia-T3KTGYLV.js",
  "./vendor/chunks/livescript-AXVP57IS.js",
  "./vendor/chunks/lua-4SA4TOHS.js",
  "./vendor/chunks/mathematica-ZRWXRXCG.js",
  "./vendor/chunks/mbox-ARNYNXGS.js",
  "./vendor/chunks/mirc-CZTHZ4FX.js",
  "./vendor/chunks/mllike-6TE5V7ID.js",
  "./vendor/chunks/modelica-3IHEDMXO.js",
  "./vendor/chunks/mscgen-KIWY66VF.js",
  "./vendor/chunks/mumps-75A72WLC.js",
  "./vendor/chunks/nginx-7ALZTXSC.js",
  "./vendor/chunks/nsis-OFD2ZGJ6.js",
  "./vendor/chunks/ntriples-Y665BLR3.js",
  "./vendor/chunks/octave-OPA5UIIT.js",
  "./vendor/chunks/oz-7VCYSMVO.js",
  "./vendor/chunks/pascal-VK5AEXN6.js",
  "./vendor/chunks/perl-77IHFFOP.js",
  "./vendor/chunks/pig-WJCMGMFX.js",
  "./vendor/chunks/powershell-SJBL6UHJ.js",
  "./vendor/chunks/properties-N2AV2NEJ.js",
  "./vendor/chunks/protobuf-LQBQI7VV.js",
  "./vendor/chunks/pug-M3XL7PMD.js",
  "./vendor/chunks/puppet-NFGSDFO4.js",
  "./vendor/chunks/python-WFSMVPYW.js",
  "./vendor/chunks/q-LKB2MKRU.js",
  "./vendor/chunks/r-2G35TBCX.js",
  "./vendor/chunks/rpm-JTDMGQNW.js",
  "./vendor/chunks/ruby-2K2YI2ME.js",
  "./vendor/chunks/sas-EWLYTO3D.js",
  "./vendor/chunks/scheme-TI6G2YWI.js",
  "./vendor/chunks/shell-S3FJJ43A.js",
  "./vendor/chunks/sieve-WWX2ZARH.js",
  "./vendor/chunks/smalltalk-WHH7QWWH.js",
  "./vendor/chunks/solr-3UMDP6EF.js",
  "./vendor/chunks/sparql-EH43LKTL.js",
  "./vendor/chunks/spreadsheet-Y26VIE3L.js",
  "./vendor/chunks/sql-MGRJXYHS.js",
  "./vendor/chunks/stex-G7N5KYOC.js",
  "./vendor/chunks/stylus-RXFBMEOS.js",
  "./vendor/chunks/swift-ASXXPSPK.js",
  "./vendor/chunks/tcl-DNJ75CQO.js",
  "./vendor/chunks/textile-KO372CRW.js",
  "./vendor/chunks/tiddlywiki-Y46CGB37.js",
  "./vendor/chunks/tiki-7BGY54BF.js",
  "./vendor/chunks/toml-4FLRZWOX.js",
  "./vendor/chunks/troff-DG76KJ3R.js",
  "./vendor/chunks/ttcn-TYHBZBZO.js",
  "./vendor/chunks/ttcn-cfg-HPI7VM5N.js",
  "./vendor/chunks/turtle-O46HSV5F.js",
  "./vendor/chunks/vb-EGLZY27U.js",
  "./vendor/chunks/vbscript-KPSBRXNL.js",
  "./vendor/chunks/velocity-WFE76VIC.js",
  "./vendor/chunks/verilog-7ORVXCA3.js",
  "./vendor/chunks/vhdl-RVJLFDKL.js",
  "./vendor/chunks/webidl-DHC4UJMW.js",
  "./vendor/chunks/xquery-D46I4U2G.js",
  "./vendor/chunks/yacas-HXNLW7GI.js",
  "./vendor/chunks/z80-MXIJZW3F.js",
  "./vendor/cm-emmet.js",
  "./vendor/cm-minimap.js",
  "./vendor/codemirror.js",
  "./vendor/codicons/codicon.css",
  "./vendor/codicons/codicon.ttf",
  "./vendor/jszip.js",
  "./vendor/markdown.js",
  "./vendor/seti.js"]; // @generated

const APP_CACHE = `${VERSION}-app`;
const RUNTIME_CACHE = 'xcoder-runtime-v1';
const RUNTIME_HOSTS = ['esm.sh', 'cdn.jsdelivr.net', 'js.puter.com', 'unpkg.com'];
const RUNTIME_MAX_ENTRIES = 400;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(APP_CACHE);
    const urls = ['./', ...PRECACHE];
    // Fetch with cache: 'reload' so we never precache stale HTTP-cached copies.
    await Promise.all(urls.map(async url => {
      try {
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (res.ok) await cache.put(url, res);
      } catch (err) { /* offline during install: the next update retries */ }
    }));
    // Upgrading from X Coder 5 (or older): take over immediately — the old worker served a different app layout.
    const keys = await caches.keys();
    if (keys.some(k => /^xcoder-v[0-5]\.|^arena-pocket-ide-/.test(k))) await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      const ours = key.startsWith('xcoder-') || key.startsWith('arena-pocket-ide-');
      if (ours && key !== APP_CACHE && key !== RUNTIME_CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  if (event.data?.type === 'skipWaiting') self.skipWaiting();
  if (event.data?.type === 'version') event.source?.postMessage({ type: 'version', version: VERSION });
});

async function trimRuntimeCache() {
  const cache = await caches.open(RUNTIME_CACHE);
  const keys = await cache.keys();
  for (const req of keys.slice(0, Math.max(0, keys.length - RUNTIME_MAX_ENTRIES))) await cache.delete(req);
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (url.origin === self.location.origin) {
    // Navigations: network first (fresh index.html), cached shell offline.
    if (req.mode === 'navigate') {
      event.respondWith((async () => {
        try {
          const fresh = await fetch(req);
          if (fresh.ok) return fresh;
          throw new Error(`HTTP ${fresh.status}`);
        } catch {
          const cache = await caches.open(APP_CACHE);
          return (await cache.match('./index.html')) || (await cache.match('./')) || new Response('X Coder is offline and not cached yet.', { status: 503, headers: { 'content-type': 'text/plain' } });
        }
      })());
      return;
    }
    // App files: serve the precached version (all modules come from the same release).
    event.respondWith((async () => {
      const cache = await caches.open(APP_CACHE);
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok && url.pathname.includes('/vendor/')) cache.put(req, res.clone()).catch(() => {});
        return res;
      } catch {
        return new Response('Offline', { status: 503, headers: { 'content-type': 'text/plain' } });
      }
    })());
    return;
  }

  // CDN libraries: stale-while-revalidate (only successful CORS responses).
  if (RUNTIME_HOSTS.includes(url.hostname)) {
    event.respondWith((async () => {
      const cache = await caches.open(RUNTIME_CACHE);
      const cached = await cache.match(req);
      const network = fetch(req).then(res => {
        if (res.ok && (res.type === 'cors' || res.type === 'basic')) {
          cache.put(req, res.clone()).then(trimRuntimeCache).catch(() => {});
        }
        return res;
      }).catch(() => cached || Response.error());
      return cached || network;
    })());
  }
  // Everything else (AI router, GitHub API, Puter API) goes straight to the network.
});
