if(!window.__XCODER_V5_LOADED__){window.__XCODER_V5_LOADED__=true;
/* X Coder 5.0 progressive enhancements.
 * Kept separate from app.js so the core IDE remains stable while mobile AI UX evolves.
 */
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const V5_TTS_KEY='xcoderTTSv5',V5_AUTO_PUSH_KEY='xcoderAutoPushAI';
const tts={provider:'auto',gender:'female',voice:'',autoSpeak:false,voices:[],audio:null,utterance:null,spoken:new Set()};
try{Object.assign(tts,JSON.parse(localStorage.getItem(V5_TTS_KEY)||'{}'));}catch{}
function saveTTS(){localStorage.setItem(V5_TTS_KEY,JSON.stringify({provider:tts.provider,gender:tts.gender,voice:tts.voice,autoSpeak:!!tts.autoSpeak}));}
function toastV5(text,type=''){const host=$('#toastHost');if(!host)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;host.append(el);setTimeout(()=>el.remove(),type==='error'?5000:2500);}
function logV5(level,source,message){console[level==='error'?'error':level==='warn'?'warn':'log'](`[X Coder ${source}]`,message);}
function cleanSpeech(text=''){return String(text).replace(/```[\s\S]*?```/g,' code block omitted ').replace(/`([^`]+)`/g,'$1').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/[#>*_~-]+/g,' ').replace(/\s+/g,' ').trim().slice(0,2900);}
function stopSpeech(){try{tts.audio?.pause?.();if(tts.audio)tts.audio.currentTime=0;}catch{}tts.audio=null;try{speechSynthesis.cancel();}catch{}tts.utterance=null;const s=$('#ttsStatusText');if(s)s.textContent='Speech stopped.';}
function guessGender(v){const n=`${v?.name||''} ${v?.voiceURI||''}`.toLowerCase();if(/samantha|victoria|karen|moira|tessa|serena|ava|allison|susan|zira|fiona|kate|joanna|salli|kimberly|ivy|emma|amy|nicole|ara|eve|nova|shimmer/.test(n))return'female';if(/daniel|alex|fred|tom|aaron|arthur|lee|rishi|david|mark|george|matthew|brian|joey|justin|rex|leo|onyx|ash|echo/.test(n))return'male';return'auto';}
function signedIn(){try{return !!window.puter?.auth?.isSignedIn?.();}catch{return false;}}
async function refreshVoices(show=false){const status=$('#ttsStatusText');if(status)status.textContent='Loading voices…';let list=[];try{if(tts.provider!=='browser'&&signedIn()&&window.puter?.ai?.txt2speech?.listVoices){const rows=await puter.ai.txt2speech.listVoices({provider:'all'});list.push(...(Array.isArray(rows)?rows:[]).filter(v=>!v.language?.code||/^en/i.test(v.language.code)).map(v=>({kind:'puter',id:String(v.id||v.name||''),name:String(v.name||v.id||'Voice'),provider:String(v.provider||''),gender:guessGender(v)})).filter(v=>v.id));}if(tts.provider!=='puter'&&'speechSynthesis'in window){const rows=speechSynthesis.getVoices?.()||[];list.push(...rows.filter(v=>!v.lang||/^en/i.test(v.lang)).map(v=>({kind:'browser',id:v.voiceURI||v.name,name:v.name,provider:'Device',gender:guessGender(v)})));}tts.voices=list;renderVoiceControls();if(status)status.textContent=list.length?`${list.length} voices available.`:'Using the default device voice.';if(show)toastV5('Voice list refreshed');}catch(e){if(status)status.textContent=`Voice lookup failed: ${e.message}`;logV5('warn','Voice',e.message);}}
function renderVoiceControls(){const p=$('#ttsProviderSelect'),v=$('#ttsVoiceSelect'),a=$('#ttsAutoSpeakToggle');if(p)p.value=tts.provider;if(a)a.checked=!!tts.autoSpeak;$$('#ttsGenderControl [data-tts-gender]').forEach(b=>b.classList.toggle('active',b.dataset.ttsGender===tts.gender));if(v){const rows=tts.voices.filter(x=>tts.gender==='auto'||x.gender===tts.gender||x.gender==='auto');v.innerHTML='<option value="">Automatic</option>'+rows.map(x=>`<option value="${x.kind}|${x.provider}|${encodeURIComponent(x.id)}">${x.name}${x.provider?` · ${x.provider}`:''}</option>`).join('');v.value=tts.voice||'';if(v.value!==tts.voice)v.value='';}}
function browserVoice(){let rows=[];try{rows=speechSynthesis.getVoices?.()||[];}catch{}if(tts.voice.startsWith('browser|')){const id=decodeURIComponent(tts.voice.split('|').slice(2).join('|'));const exact=rows.find(v=>(v.voiceURI||v.name)===id);if(exact)return exact;}const en=rows.filter(v=>!v.lang||/^en/i.test(v.lang)),filtered=en.filter(v=>tts.gender==='auto'||guessGender(v)===tts.gender);return filtered.find(v=>v.localService)||filtered[0]||en[0]||rows[0]||null;}
async function browserSpeak(text){if(!('speechSynthesis'in window))throw new Error('Speech synthesis is unavailable in this browser.');stopSpeech();return new Promise((resolve,reject)=>{const u=new SpeechSynthesisUtterance(text),voice=browserVoice();if(voice)u.voice=voice;u.rate=.96;u.pitch=tts.gender==='female'?1.03:tts.gender==='male'?.96:1;u.onend=resolve;u.onerror=e=>reject(new Error(e.error||'Speech failed'));tts.utterance=u;speechSynthesis.speak(u);});}
async function puterSpeak(text){if(!signedIn()||!window.puter?.ai?.txt2speech)throw new Error('Sign in to X Coder Cloud for natural Puter voices.');let provider='xai',voice='';if(tts.voice.startsWith('puter|')){const p=tts.voice.split('|');provider=p[1]||'xai';voice=decodeURIComponent(p.slice(2).join('|'));}if(!voice){const rows=tts.voices.filter(x=>x.kind==='puter'&&(tts.gender==='auto'||x.gender===tts.gender));const names=tts.gender==='male'?['Rex','Leo','Onyx','Ash','Echo']:tts.gender==='female'?['Ara','Eve','Nova','Shimmer','Alloy']:['Sal','Alloy'];const pick=names.map(n=>rows.find(v=>new RegExp(`^${n}$`,'i').test(v.name)||new RegExp(`^${n}$`,'i').test(v.id))).find(Boolean)||rows.find(v=>v.provider==='xai')||rows[0];if(pick){provider=pick.provider||'xai';voice=pick.id;}}const opts={provider};if(voice)opts.voice=voice;const audio=await puter.ai.txt2speech(text,opts);tts.audio=audio;await audio.play();}
async function speak(text){const clean=cleanSpeech(text);if(!clean)return;stopSpeech();const status=$('#ttsStatusText');if(status)status.textContent='Preparing voice…';try{if(tts.provider==='puter'||(tts.provider==='auto'&&signedIn()))await puterSpeak(clean);else await browserSpeak(clean);if(status)status.textContent='Speaking…';}catch(e){if(tts.provider==='puter')throw e;logV5('warn','Voice',`Natural voice fallback: ${e.message}`);await browserSpeak(clean);if(status)status.textContent='Using device voice fallback.';}}
function enhanceMessages(){const host=$('#aiMessages');if(!host)return;$$('.ai-message.assistant',host).forEach((row,i)=>{if(row.dataset.v5Voice==='1')return;row.dataset.v5Voice='1';const meta=row.querySelector('.ai-meta'),bubble=row.querySelector('.ai-bubble');if(meta&&bubble){const b=document.createElement('button');b.className='ai-speak-btn';b.type='button';b.setAttribute('aria-label','Read reply aloud');b.title='Read aloud';b.innerHTML='◖))';b.addEventListener('click',()=>speak(bubble.innerText).catch(e=>toastV5(e.message,'error')));meta.append(b);}if(tts.autoSpeak&&!tts.spoken.has(row)){tts.spoken.add(row);setTimeout(()=>speak(bubble?.innerText||'').catch(()=>{}),120);}});}
function wrapPuterReasoning(){const tryWrap=()=>{const ai=window.puter?.ai;if(!ai?.chat||ai.chat.__xcoderV5)return false;const original=ai.chat.bind(ai);const wrapped=function(...args){const last=args[args.length-1];if(last&&typeof last==='object'&&!Array.isArray(last)&&!(last instanceof Blob)){if(last.reasoning_effort==null&&last.reasoning?.effort==null)last.reasoning_effort='high';}return original(...args);};wrapped.__xcoderV5=true;ai.chat=wrapped;return true;};if(!tryWrap()){let n=0;const id=setInterval(()=>{if(tryWrap()||++n>30)clearInterval(id);},300);}}
function quickOptions(){const select=$('#aiModelSelect');if(!select)return[];const opts=[...select.options].map(o=>({value:o.value,text:(o.textContent||'').trim()}));const out=[],used=new Set();const add=(label,re)=>{const o=opts.find(x=>re.test(x.text)&&!used.has(x.value));if(o){out.push({label,detail:o.text,value:o.value});used.add(o.value);}};const auto=opts.find(x=>x.value==='auto')||opts[0];if(auto){out.push({label:'Auto',detail:'Best available route',value:auto.value});used.add(auto.value);}add('ChatGPT',/gpt|openai|codex/i);add('Gemini',/gemini/i);add('Claude',/claude|anthropic/i);add('Grok',/grok|xai/i);add('Coder',/coder|codestral|devstral|qwen/i);const current=select.options[select.selectedIndex];if(current&&!used.has(current.value))out.push({label:'Current',detail:current.textContent.trim(),value:current.value});return out.slice(0,7);}
const qp={open:false,timer:null,pointer:null,long:false,active:-1};
function renderQuick(){const host=$('#aiQuickModelList'),select=$('#aiModelSelect');if(!host||!select)return;host.innerHTML=quickOptions().map((x,i)=>`<button class="quick-model-item ${x.value===select.value?'selected':''}" data-model-value="${encodeURIComponent(x.value)}" data-q-index="${i}"><span class="quick-model-check">${x.value===select.value?'✓':''}</span><span class="quick-model-copy"><strong>${x.label}</strong><small>${x.detail}</small></span></button>`).join('');}
function openQuick(id){renderQuick();const p=$('#aiQuickModelPicker');p?.classList.remove('hidden');requestAnimationFrame(()=>p?.classList.add('open'));qp.open=true;qp.pointer=id;qp.active=-1;navigator.vibrate?.(10);}
function setActive(i){qp.active=i;$$('.quick-model-item','#aiQuickModelPicker').forEach((b,n)=>b.classList.toggle('hovered',i===n));}
function selectModel(v){const s=$('#aiModelSelect');if(!s)return;s.value=v;s.dispatchEvent(new Event('change',{bubbles:true}));renderQuick();}
function closeQuick(commit=false){const p=$('#aiQuickModelPicker');if(commit&&qp.active>=0){const b=$$('.quick-model-item',p)[qp.active];if(b)selectModel(decodeURIComponent(b.dataset.modelValue));}p?.classList.remove('open');setTimeout(()=>p?.classList.add('hidden'),130);qp.open=false;qp.pointer=null;qp.active=-1;}
function pointerIndex(e){const rows=$$('.quick-model-item','#aiQuickModelPicker');let best=-1,d=1e9;rows.forEach((b,i)=>{const r=b.getBoundingClientRect(),cy=(r.top+r.bottom)/2,dist=Math.abs(e.clientY-cy);if(e.clientX>=r.left-34&&e.clientX<=r.right+34&&dist<d){d=dist;best=i;}});return d<52?best:-1;}

function ensureV5UI(){
  const send=$('#aiSendBtn');
  if(send){
    send.classList.add('model-hold-button');
    send.setAttribute('aria-label','Send to X Coder AI. Hold to choose model.');
    send.title='Tap to send · hold to choose model';
    if(!send.querySelector('.model-hold-caret'))send.insertAdjacentHTML('beforeend','<span class="model-hold-caret" aria-hidden="true"></span>');
    const composer=send.closest('.ai-composer');
    const wrap=composer?.parentElement;
    if(wrap&&!wrap.querySelector('.ai-hold-hint'))composer.insertAdjacentHTML('afterend','<div class="ai-hold-hint">Hold send to switch model</div>');
  }
  if(!$('#aiQuickModelPicker')){
    document.body.insertAdjacentHTML('beforeend','<div id="aiQuickModelPicker" class="ai-quick-model-picker hidden" role="menu" aria-label="Quick model switcher"><div class="quick-model-title">Choose model</div><div id="aiQuickModelList" class="quick-model-list"></div><div class="quick-model-hint">Slide to choose · release to select</div></div>');
  }
  if(!$('#gitAutoPushToggle')){
    const push=$('#gitPushBtn');
    if(push)push.insertAdjacentHTML('afterend','<label class="toggle-row git-auto-push-row"><span><strong>Auto-push approved AI edits</strong><small>After you approve and apply an AI change, X Coder can commit and push it using the repository and GitHub token configured above.</small></span><input id="gitAutoPushToggle" type="checkbox" /></label>');
  }
  if(!$('#ttsProviderSelect')){
    const puterRow=$('#puterSignInBtn')?.closest('.settings-row');
    if(puterRow)puterRow.insertAdjacentHTML('afterend',`<div class="settings-row settings-row-stack voice-settings-row">
      <div class="settings-row-copy"><strong>Voice</strong><span>Read X Coder replies aloud. Natural Puter voices are used when available, with the device voice as a fallback.</span></div>
      <label class="field-label">Speech engine<select id="ttsProviderSelect" class="settings-select"><option value="auto">Automatic</option><option value="puter">Puter natural voice</option><option value="browser">Device voice</option></select></label>
      <div class="field-label">Voice style<div id="ttsGenderControl" class="segmented-control voice-segmented" role="radiogroup" aria-label="Voice style"><button type="button" data-tts-gender="female">Female</button><button type="button" data-tts-gender="male">Male</button><button type="button" data-tts-gender="auto">Auto</button></div></div>
      <label class="field-label">Available voice<select id="ttsVoiceSelect" class="settings-select"><option value="">Automatic</option></select></label>
      <label class="toggle-row"><span>Speak AI replies automatically</span><input id="ttsAutoSpeakToggle" type="checkbox" /></label>
      <div class="button-row wrap"><button id="ttsRefreshBtn" class="secondary-btn">Refresh Voices</button><button id="ttsTestBtn" class="secondary-btn">Preview Voice</button><button id="ttsStopBtn" class="secondary-btn">Stop</button></div>
      <span id="ttsStatusText" class="row-description">Voice is ready.</span>
    </div>`);
  }
}
function bindQuickPicker(){const b=$('#aiSendBtn');if(!b||b.dataset.v5Hold==='1')return;b.dataset.v5Hold='1';b.addEventListener('pointerdown',e=>{qp.long=false;qp.pointer=e.pointerId;clearTimeout(qp.timer);qp.timer=setTimeout(()=>{qp.long=true;openQuick(e.pointerId);try{b.setPointerCapture(e.pointerId);}catch{}},420);},{capture:true});b.addEventListener('pointermove',e=>{if(!qp.open||e.pointerId!==qp.pointer)return;e.preventDefault();setActive(pointerIndex(e));},{capture:true});b.addEventListener('pointerup',e=>{clearTimeout(qp.timer);if(qp.open){e.preventDefault();e.stopImmediatePropagation();closeQuick(true);setTimeout(()=>qp.long=false,80);}},{capture:true});b.addEventListener('pointercancel',()=>{clearTimeout(qp.timer);if(qp.open)closeQuick(false);qp.long=false;},{capture:true});b.addEventListener('click',e=>{if(qp.long){e.preventDefault();e.stopImmediatePropagation();qp.long=false;}},{capture:true});b.addEventListener('contextmenu',e=>e.preventDefault());$('#aiQuickModelPicker')?.addEventListener('click',e=>{const x=e.target.closest('[data-model-value]');if(x){selectModel(decodeURIComponent(x.dataset.modelValue));closeQuick(false);}});}
function bindTTS(){renderVoiceControls();$('#ttsProviderSelect')?.addEventListener('change',e=>{tts.provider=e.target.value;tts.voice='';saveTTS();refreshVoices(true);});$('#ttsVoiceSelect')?.addEventListener('change',e=>{tts.voice=e.target.value;saveTTS();});$('#ttsAutoSpeakToggle')?.addEventListener('change',e=>{tts.autoSpeak=e.target.checked;saveTTS();});$$('#ttsGenderControl [data-tts-gender]').forEach(b=>b.addEventListener('click',()=>{tts.gender=b.dataset.ttsGender;tts.voice='';saveTTS();renderVoiceControls();}));$('#ttsRefreshBtn')?.addEventListener('click',()=>refreshVoices(true));$('#ttsTestBtn')?.addEventListener('click',()=>speak('Hi, I am X Coder. This is a preview of the selected voice.').catch(e=>toastV5(e.message,'error')));$('#ttsStopBtn')?.addEventListener('click',stopSpeech);try{speechSynthesis.addEventListener?.('voiceschanged',()=>{if(tts.provider!=='puter')refreshVoices(false);});}catch{}}
function bindAutoPush(){const toggle=$('#gitAutoPushToggle');if(!toggle)return;toggle.checked=localStorage.getItem(V5_AUTO_PUSH_KEY)==='1';toggle.addEventListener('change',()=>{localStorage.setItem(V5_AUTO_PUSH_KEY,toggle.checked?'1':'0');toastV5(toggle.checked?'AI auto-push enabled':'AI auto-push disabled');});}
let lastReport='';function maybeAutoPush(){const toggle=$('#gitAutoPushToggle');if(!toggle?.checked)return;const reports=$$('.ai-message.assistant');const row=reports.at(-1);if(!row)return;const meta=row.querySelector('.ai-meta')?.innerText||'',text=row.querySelector('.ai-bubble')?.innerText||'';if(!/Verified implementation report/i.test(meta)||text===lastReport)return;lastReport=text;const repo=$('#gitRepoInput')?.value?.trim(),token=$('#gitTokenInput')?.value||sessionStorage.getItem('githubToken');if(!repo||!token){logV5('warn','Git','Auto-push skipped: configure repository and token in Git first.');return;}const commit=$('#gitCommitInput');if(commit&&!commit.value.trim())commit.value='AI update from X Coder';setTimeout(()=>$('#gitPushBtn')?.click(),700);}
function startObservers(){const ai=$('#aiMessages');if(ai)new MutationObserver(()=>{enhanceMessages();maybeAutoPush();}).observe(ai,{childList:true,subtree:true});const select=$('#aiModelSelect');if(select)new MutationObserver(renderQuick).observe(select,{childList:true,subtree:true});enhanceMessages();}
function initV5(){ensureV5UI();wrapPuterReasoning();bindQuickPicker();bindTTS();bindAutoPush();startObservers();refreshVoices(false);renderQuick();document.documentElement.dataset.xcoderVersion='5.0.0';}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initV5,{once:true});else initV5();

}
